2023HERETHON/HERETHON/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('account/',include('account.urls')),
    path('template/',include('template.urls')),
    path('contact/',include('contact.urls')),
]

2023HERETHON/account/urls.py
from django.urls import path
from account import views
from account.views import *

app_name = 'account'

urlpatterns = [
    path('login/', views.login, name="login"),
    path('signup/', views.signup, name="signup"),
    path('logout/', views.logout, name='logout'),
    path('do_duplicate_check/',views.do_duplicate_check,name='do_duplicate_check'),
]

2023HERETHON/contact/urls.py
from django.urls import path
from contact import views
from contact.views import *

app_name = 'contact'

urlpatterns = [
    path("main/", views.contact, name="contact_list"),
    path("addPage/",views.contact_add_page,name="addPage"),
    path("add/",views.contact_add,name="add"),
    path("delete/<int:id>",views.contact_delete,name="delete"),
]

2023HERETHON/template/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name='template'                  # app name작성 후 view와 url연결

urlpatterns = [
    path("main/<int:cate>/<int:ord>", mainView,name="main"),
    path('mail/<int:temp_id>/',mailView,name="mail"),
    path('template/addpage/<int:cate>/',addPageView,name="addPage"),
    path('template/add/<int:cate>/',addView,name="add"),
    path('template/updatepage/<int:temp_id>',updatePageView,name="updatePage"),
    path('template/update/<int:temp_id>',updateView,name="update"),
    path('delete/<int:temp_id>/',deleteView,name="delete"),
    path('search/',searchView,name="search"),
]

2023HERETHON/account/models.py
from django.db import models
from django.contrib.auth.models import User

2023HERETHON/contact/models.py
from django.db import models
from account.models import User

# Create your models here.

class Contact(models.Model):
    id = models.AutoField(primary_key=True)
    con_user = models.ForeignKey(User,related_name='con_user',on_delete=models.CASCADE)
    subject = models.CharField(max_length=30, null=True)
    professor_name = models.CharField(max_length=10, null=True)
    email = models.EmailField(max_length=100)
    
    def __str__(self):
        return "{}:{}-{}".format(self.id,self.professor_name,self.subject)

2023HERETHON/template/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

class Template(models.Model):
    class Cate(models.IntegerChoices):
        SCHOOL = 1
        CLUB = 2
        BASE = 3
        MY = 4

    id = models.AutoField(primary_key=True)
    cate = models.IntegerField(choices=Cate.choices)
    title = models.TextField(blank=True)
    greet = models.TextField(blank=True)    # 인사말
    intro = models.TextField(blank=True)    # 용건
    content = models.TextField(blank=True)  # 내용
    bye = models.TextField(blank=True)      # 끝인사
    is_base = models.BooleanField(default=False)
    created_at=models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "{}:{}-{}".format(self.cate,self.id,self.title)

2023HERETHON/account/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import auth
#from django.contrib import messages

def login(request):
    cate=1
    if request.method == "POST":
        userid = request.POST['username']
        pwd = request.POST['password']
        user = auth.authenticate(request, username=userid, password=pwd)
        if user is not None:
            auth.login(request, user)
            ord=1
            return redirect('template:main', cate,ord)
        else:
            return render(request, 'login.html', {'error': '입력한 내용을 다시 확인해주세요.'})
    else: 
        return render(request, 'login.html')

def signup(request):
    if request.method == 'POST':
        userid = request.POST['userid']
        username = request.POST['userName']
        password = request.POST['password']
        password2 = request.POST['password2']
        
        if User.objects.filter(username=userid).exists():
            #messages.error(request, '이미 존재하는 아이디입니다.')
            return render(request, 'signup.html', {'error': '이미 존재하는 아이디입니다.'})

        if request.POST['password'] == request.POST['password2']:
            user = User.objects.create_user(username=request.POST['userid'], password=request.POST['password'],first_name=request.POST['userName'])
            auth.login(request, user)
            return render(request, 'login.html')
        else:
            return render(request, 'signup.html')
        
    return render(request, 'signup.html')

def logout(request):
    auth.logout(request)
    return render(request, 'login.html')

def do_duplicate_check(request):
    print('아이디 중복 확인')
    userid=request.GET.get('user_id')
    if User.objects.filter(username=userid).exists():
            duplicate = "fail"
    else: duplicate = "pass"
    context={'duplicate':duplicate}
    return JsonResponse(context)

2023HERETHON/contact/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Contact

def contact(request):
    if request.user.is_authenticated:
        print("로그인 상태")
        print("Username --> {request.user.username}")

    else:
        print("로그인 되어있지 않음")
        return redirect("account:login")
    now_user=request.user
    contacts = Contact.objects.filter(con_user=now_user)
    return render(request, "contact.html", {"contacts":contacts})

def contact_add_page(request):
    return render(request, "contact_create.html")

def contact_add(request):
    now_user=request.user
    print(now_user)
    newcontact=Contact()
    newcontact.professor_name=request.POST['professor_name']
    newcontact.subject=request.POST['subject']
    newcontact.email=request.POST['email']
    newcontact.con_user=now_user
    newcontact.save()
    return redirect('contact:contact_list')

def contact_delete(request, id):
    del_contact=get_object_or_404(Contact,pk=id)
    del_contact.delete()
    return redirect('contact:contact_list')

2023HERETHON/template/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Template
from django.db.models import Q

# Create your views here.

def mainView(request,cate,ord):
    temps_bases=Template.objects.filter(cate=cate,is_base=True)   # 기본 제공 템플릿
    # 추가된 템플릿
    if(ord==1): # 최신순
        temps=Template.objects.filter(cate=cate,is_base=False).order_by('-created_at')       
    else:       # 제목 가나다순
        temps=Template.objects.filter(cate=cate,is_base=False).order_by('title')
    return render (request,'main.html',{'temps_bases':temps_bases,'temps':temps,'cate':cate,'ord':ord})

def mailView(request,temp_id):
    temp=get_object_or_404(Template,id=temp_id)
    cate=temp.cate
    is_base=temp.is_base
    if(cate==3):
        return render (request,'write_basic.html',{'temp':temp,'is_base':is_base})
    return render (request,'write.html',{'temp':temp,'is_base':is_base})

def deleteView(request,temp_id):
    del_temp=get_object_or_404(Template,id=temp_id)
    del_cate=del_temp.cate
    del_temp.delete()
    return redirect('template:main',cate=del_cate,ord=1)

def addPageView(request,cate):
    if(cate==3):
        return render (request,'add_basic.html',{'cate':cate})
    return render (request,'add.html',{'cate':cate})

def addView(request,cate):
    new_temp=Template()
    new_temp.title=request.POST['title']
    new_temp.greet=request.POST['greet']
    new_temp.intro=request.POST['intro']
    new_temp.content=request.POST['content']
    new_temp.bye=request.POST['bye']
    new_temp.cate=cate
    new_temp.save()
    return redirect('template:main',cate=cate,ord=1)

def updatePageView(request,temp_id):
    update_temp=get_object_or_404(Template,id=temp_id)
    cate=update_temp.cate
    if(cate==3):
        return render (request,'update_basic.html',{'temp':update_temp,'temp_id':temp_id})
    return render (request,'update.html',{'temp':update_temp,'temp_id':temp_id})

def updateView(request,temp_id):
    update_temp=get_object_or_404(Template,id=temp_id)
    cate=update_temp.cate
    update_temp.title=request.POST['title']
    update_temp.greet=request.POST['greet']
    update_temp.intro=request.POST['intro']
    update_temp.content=request.POST['content']
    update_temp.bye=request.POST['bye']
    update_temp.save()
    return redirect('template:main',cate=cate,ord=1)

def searchView(request):
    search=request.GET.get('search','')
    search_temps=Template.objects.filter(        #제목 또는 내용에 search가 있는것 필터링 #2
     Q(title__icontains = search) | Q(intro__icontains = search)| Q(content__icontains = search)| Q(bye__icontains = search)
    )
    return render(request,'search.html',{'temps':search_temps})

2023HERETHON/account/templates/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>회원가입</title>
    {% load static %}
  </head>

  <style>
    body {
      /*전체 body 태그*/
      font-family: "Noto Sans KR", sans-serif;
      align-items: center;
    }

    .signup-form {
      /*전체 화면을 포함하는 section 박스*/
      align-items: center;
      position: absolute;
      width: 550px;
      height: 1100px;
      background: #e6e2dd;
      margin-left: 40%;
    }

    #content {
      /*회원가입 템플릿을 포함하는 div 태그*/
      margin-top: 60px;
    }

    .signup-form h1 {
      /*상단 "회원가입" 문구 h1*/
      margin-left: 50px;
      margin-top: 10px;
      margin-bottom: 80px;
      font-size: 45px;
      text-align: left;
      line-height: 120%;
      text-shadow: 2px 2px 6px gray;
    }

    label {
      /*각각의 입력칸에 해당되는 label 태그*/
      margin-left: 50px;
      margin-bottom: 5px;
      font-size: 30px;
    }

    .int-area {
      /*각각의 입력칸을 포함하는 div태그 */
      width: 400px;
      position: relative;
      margin-top: 30px;
      margin-left: 60px;
    }

    .int-area input {
      /*각각의 input 태그*/
      width: 90%;
      padding: 30px 40px 30px;
      background-color: transparent;
      border: none;
      background-color: #ffffff;
      border-radius: 40px;
      font-size: 25px;
      outline: none;
      margin-top: 0px;
      margin-bottom: 10px;
    }

    #check {
      /*중복확인 버튼*/
      position: absolute;
      width: 25%;
      padding: 15px;
      top: 0px;
      left: 340px;
      height: 90px;
      color: #ffffff;
      background: #79b4bd;
      border: none;
      border-radius: 40px;
      font-size: 20px;
      font-weight: bold;
      display: inline-block;
    }

    .overlap_msg {
      position: absolute;
      left: 270px;
      top: 510px;
      color: red;
    }

    .pw_check_msg {
      position: absolute;
      left: 270px;
      top: 850px;
      color: red;
    }

    #red {
      /*각각의 라벨 옆 *을 나타내는 span 태그 색깔 조정*/
      color: red;
    }

    .btn-area {
      /*등록 버튼을 포함하는 div 태그*/
      margin-top: 30px;
      margin-left: 50px;
    }

    .btn-area button {
      /*등록 버튼*/
      width: 90%;
      height: 90px;
      font-weight: bold;
      margin-top: 20px;
      color: #fff;
      background: #79b4bd;
      border: none;
      border-radius: 40px;
      font-size: 30px;
      cursor: pointer;
    }
  </style>

  <body>
    <section class="signup-form">
      <!--전체화면을 포함하는 박스-->
      <div id="content">
        <div>
          <h1>회원가입</h1>
        </div>

        <form method="post" action="{% url 'account:signup' %}">
          {% csrf_token %}
          <label for="name">이름<span id="red">*</span></label>
          <div class="int-area">
            <!--이름 입력칸-->
            <input
              type="text"
              name="userName"
              id="userName"
              placeholder="이름을 입력하세요"
              autocomplete="off"
              required
            />
          </div>

          <label for="userid">아이디<span id="red">*</span></label>
          <div class="int-area">
            <!--아이디 입력칸-->
            <input
              type="text"
              name="userid"
              id="user_id"
              placeholder="아이디를 입력해주세요"
              autocomplete="off"
              required
            />
            <div>
              <img
                style="
                  position: absolute;
                  top: 0;
                  right: -19px;
                  height: 45px;
                  margin-top: 20px;
                  margin-left: 0;
                "
                src="{% static 'img/check.png' %}"
              />
              <button
                style="position: absolute; top: 0; right: 0px"
                id="check"
                type="button"
                class="id_overlap_button"
                onclick="id_overlap_check()"
              >
                중복<br />확인
              </button>
            </div>
          </div>
          <p class="overlap_msg" style="display: none">
            이미 존재하는 아이디입니다.
          </p>
          <label for="password">비밀번호<span id="red">*</span></label>
          <div class="int-area">
            <!--비밀번호 입력칸-->
            <input
              type="password"
              name="password"
              id="password"
              placeholder="비밀번호를 입력해주세요"
              autocomplete="off"
              required
            />
          </div>

          <label for="password2">비밀번호 확인<span id="red">*</span></label>
          <div class="int-area">
            <!--비밀번호 확인 재입력칸-->
            <input
              type="password"
              name="password2"
              id="password2"
              placeholder="비밀번호를 다시 입력해주세요"
              autocomplete="off"
              onkeyup="pw_msg()"
              required
            />
          </div>
          <p class="pw_check_msg" style="display: none">
            비밀번호가 일치하지 않습니다.
          </p>

          <div class="btn-area">
            <!--등록 버튼-->
            <button id="btn" type="submit" onclick="pwcheck()">등록</button>
            <!--클릭하면 pwcheck() 비밀번호 체크 (js)-->
          </div>
        </form>
      </div>
    </section>
    <script>
      var error = "{{ error }}";
      if (error) {
        alert(error);
      }
    </script>
    <script src="{% static 'js/loginAlert.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script type="text/javascript">
      function pw_msg() {
        var p1 = document.getElementById("password").value;
        var p2 = document.getElementById("password2").value;

        if (p1 !== p2) {
          $(".pw_check_msg").show();
          pw_msg();
        } else {
          $(".pw_check_msg").hide();
        }
      }

      function pwcheck() {
        if ($(".id_overlap_button").is(":visible")) {
          alert("아이디 중복확인을 해주세요");
          return;
        }
        var p1 = document.getElementById("password").value;
        var p2 = document.getElementById("password2").value;

        if (p1 != "" && p1 == p2) {
          alert("회원가입이 완료되었습니다.");
        } else if (p1 != p2) {
          alert("비밀번호가 일치하지 않습니다.");
        }
      }

      function id_overlap_check() {
        var user_id = document.getElementById("user_id").value;
        if (user_id != "") {
          $.ajax({
            url: "{% url 'account:do_duplicate_check' %}",
            data: { user_id: user_id },
            datatype: "json",
            success: function (data) {
              if (data["duplicate"] == "fail") {
                $(".id_overlap_button").show();
                $(".overlap_msg").show();
                return;
              } else {
                $(".id_overlap_button").hide();
                $(".overlap_msg").hide();
                return;
              }
            },
          });
        }
      }
    </script>
  </body>
</html>

2023HERETHON/contact/templates/contact.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>메인페이지-연락망</title>
    {% load static %}
  </head>

  <style>
    #container {
      position: absolute;
      width: 550px;
      height: 1100px;
      background: #e6e2dd;

      margin-left: 40%;
    }
    /* 07/14 추가 ~ */
    #personal {
      padding: 20px;
      height: 20px;
    }

    #personal-name {
      display: inline-block;
      width: 70px;
      height: 30px;

      color: #322929;
      text-align: center;
      text-shadow: 4px 4px 4px rgba(0, 0, 0, 0.25);
      font-family: Inter;
      font-size: 22px;
      font-style: normal;
      font-weight: 700;
      line-height: normal;
    }

    #nim-text {
      display: inline-block;
      width: 30px;
      height: 30px;
      color: #fff;
      text-align: center;
      text-shadow: 4px 4px 4px rgba(0, 0, 0, 0.25);
      font-family: Inter;
      font-size: 20px;
      font-style: normal;
      font-weight: 700;
      line-height: normal;
    }

    #logout-btn {
      width: 95px;
      height: 37px;

      margin-left: 300px;
      border: none;
      background-color: #00000000;

      color: #fff;
      font-family: Inter;
      font-size: 20px;
      font-style: normal;
      font-weight: 700;
      line-height: normal;
      text-decoration-line: underline;
    }
    #logo-img{
      margin-left: 230px;
      margin-top: -50px;
    }

    /* ~ 까지 */
    #top-box {
      position: absolute;
      width: 550px;
      /* 07/15 수정 */
      height: 280px;
      border-radius: 0px 0px 40px 40px;
      background: #79b4bd;
      box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
    }

    #service-name {
      /* 07/14 수정 11:15분*/
      display: inline-block;
      width: 260px;
      height: 80px;
      flex-shrink: 0;

      margin-left: 140px;

      margin-top: -40px;

      background: #fff;
    }

    #search {
      position: relative;
      width: 440px;
      height: 55px;

      margin-left: 55px;
      margin-top: 20px;

      border: none;
      border-radius: 15px;
      background: #fff;

      color: #b2b2b2;
      font-family: Inter;
      font-size: 18px;
      font-style: normal;
      font-weight: 400;
      line-height: normal;
    }

    #img-box {
      position: relative;
      margin-left: 455px;
      margin-top: -46px;
    }

    /* 07/15 */
    #btn-box {
      width: 550px;
      height: 64px;

      margin-top: 25px;
      margin-left: 16px;
    }
    /* //고침 */
    #contect-btn {
      width: 90px;
      height: 47px;

      margin: 5px;

      border: none;
      border-radius: 23px;
      background: rgba(178, 205, 209, 0.61);
      box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);

      color: #fff;
      text-align: center;
      font-family: Inter;
      font-size: 19px;
      font-style: normal;
      font-weight: 700;
      line-height: normal;
    }
    /* 고친부분 */
    .else-btn {
      width: 90px;
      height: 47px;
      flex-shrink: 0;

      margin: 5px;

      border: none;
      border-radius: 23px;
      background: #fff;

      color: #000;
      text-align: center;
      font-family: Inter;
      font-size: 19px;
      font-style: normal;
      font-weight: 700;
      line-height: normal;
    }

    #temp-contain {
      overflow-y: scroll;
      display: flex;

      -ms-overflow-style: none; /* 인터넷 익스플로러 */
      scrollbar-width: none; /* 파이어폭스 */

      width: 490px;
      height: 300px;

      flex-wrap: wrap;
      justify-content: space-between;

      padding: 10px;
      margin-top: 330px;
      margin-left: 10px;
    }

    #temp-contain::-webkit-scrollbar {
      display: none; /* Chrome, Safari, Opera 등 웹킷 기반 브라우저 */
    }

    #mail-box {
      width: 400px;
      height: 60px;

      padding-left: 10px;
      padding-top: 10px;

      margin-left: 55px;

      border-radius: 10px;
      background: rgba(198, 213, 213, 0.61);
      box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
    }

    .professor-text {
      display: inline-block;

      color: #000;
      text-align: center;
      font-family: Inter;
      font-size: 18px;
      font-style: normal;
      font-weight: 900;
      line-height: normal;
    }

    #trash-box {
       margin-left:340px;
       margin-top:-40px;
    }
    #add-img {
      margin-top: 50px;
      margin-left: 250px;
    }
  </style>

  <body>
    <div id="container">
      <div id="top-box">
        <!-- 07/14 수정 한 곳 -->
        {% if user.is_authenticated %}

        <div id="personal">
          <div id="personal-name">{{user.first_name}}</div>
          <div id="nim-text">님</div>
          <button id="logout-btn" onclick="location.href='/account/logout/'">
            로그아웃
          </button>
        </div>
        {% endif %}
        <img id = "logo-img" src="{% static 'img/logo.png' %}" style = "width:100px;height:100px">
    
        <!-- 검색어 기능이 있는 박스 -->
        <div id="search-box">
            <form method="GET" action="{% url 'template:search' %}">
              <input
                id="search"
                name="search"
                type="title"
                placeholder="템플릿을 검색하세요"
              />
            </form>
  
            <div id="img-box">
              <img
                id="search-img "
                src="{% static 'img/gg_search.png' %}"
                style="width: 35px; height: 35px"
              />
            </div>
        </div>
        <!-- 고침까지 -->
        <div id="btn-box">
          <button
            class="else-btn"
            id="school-btn"
            onclick="location.href='/template/main/1/1'"
          >
            학교
          </button>
          <button
            class="else-btn"
            id="dong-btn"
            onclick="goOtherPage('dong-btn')"
          >
            동아리
          </button>
          <button
            class="else-btn"
            id="basic-btn"
            onclick="location.href='/template/main/2/1'"
          >
            기본
          </button>
          <button class="else-btn" id="my-btn" onclick="location.href='/template/main/3/1'">
            공유
          </button>
          <button id="contect-btn" onclick="location.href='/contact/main/'">
            연락망
          </button>
        </div>
      </div>

      <div id="temp-contain">
        {%for contact in contacts%}
            <div id="mail-box">
                <!-- professor subject address만 입력 받는 것-->
                <div class="professor-text" id="professor">{{contact.professor_name}}</div>
                <div class="professor-text">교수님 - </div>
                <div class="professor-text" id="subject">{{contact.subject}}</div>
                <div id="address">{{contact.email}}</div>
                <div id = trash-box>
                    <a href="{% url 'contact:delete' contact.id %}"><img
                        id="trash-img"
                        src="{% static 'img/trash.png' %}"
                        style="width: 35px; height: 38px"
                    /></a>
                
                </div>
            </div>
        {%endfor%}
      </div>
      <!-- 추가 버튼 --> 
      <div>
                    
        <a href="{% url 'contact:addPage' %}"><img
            id="add-img"
            src="{% static 'img/icons8_plus.png' %}"
            style="width: 55px; height: 55px"
          /></a>
        
      </div>
    </div>
      
   
  </body>
</html>

2023HERETHON/template/templates/search.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>메인페이지</title>
    {% load static %}
  </head>

  <style>
    #container {
      position: absolute;
      width: 550px;
      height: 1100px;
      background: #e6e2dd;

      margin-left: 40%;
    }
    #top-box {
      position: absolute;
      width: 550px;
      height: 290px;
      border-radius: 0px 0px 40px 40px;
      background: #79b4bd;
      box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
    }
    /* 고침 */
    #logo-img{
      margin-left: 230px;
      margin-top: -10px;
    }
    /* 고침 */
    #search {
      position: relative;
      width: 440px;
      height: 55px;

      margin-left: 55px;
      margin-top: 20px;

      border: none;
      border-radius: 15px;
      background: #fff;

      color: #b2b2b2;
      font-family: Inter;
      font-size: 18px;
      font-style: normal;
      font-weight: 400;
      line-height: normal;
    }
    /* 추가 */
    #img-box {
      position: relative;
      margin-left: 455px;
      margin-top: -46px;
    }

    /* 고친부분 */
    #btn-box {
      width: 550px;
      height: 64px;

      margin-top: 25px;
      margin-left: 16px;
    }
    /* //고침 */
    #school-btn {
      width: 90px;
      height: 47px;

      margin-left: 5px;

      border: none;
      border-radius: 23px;
      background: rgba(178, 205, 209, 0.61);
      box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);

      color: #fff;
      text-align: center;
      font-family: Inter;
      font-size: 19px;
      font-style: normal;
      font-weight: 700;
      line-height: normal;
    }
    /* 고친부분 */
    .else-btn {
      width: 90px;
      height: 47px;
      flex-shrink: 0;

      margin-left: 5px;

      border: none;
      border-radius: 23px;
      background: #fff;

      color: #000;
      text-align: center;
      font-family: Inter;
      font-size: 19px;
      font-style: normal;
      font-weight: 700;
      line-height: normal;
    }

    #temp-contain {
      overflow-y: scroll;
      display: flex;

      -ms-overflow-style: none; /* 인터넷 익스플로러 */
      scrollbar-width: none; /* 파이어폭스 */
      /* 고친부분 */
      width: 490px;
      height: 450px;

      flex-wrap: wrap;
      justify-content: space-between;

      padding: 10px;
      margin-top: 320px;
      margin-left: 10px;
    }

    #temp-contain::-webkit-scrollbar {
      display: none; /* Chrome, Safari, Opera 등 웹킷 기반 브라우저 */
    }

    .box {
      /* 고친부분 */
      position: relative;
      width: 210px;
      height: 160px;

      margin-left: 20px;
      margin-bottom: 30px;

      display: flex;
      align-items: center;
      justify-content: center;

      border-radius: 10px;
      background: rgba(178, 205, 209, 0.61);
      box-shadow: 0px 4px 4px 0px rgba(0, 0, 0, 0.25);
    }

    .title {
      color: #000;

      text-align: center;
      font-family: Inter;
      font-size: 20px;
      font-style: normal;
      font-weight: 600;
      line-height: normal;
    }

    .temp-edit-img {
      position: absolute;
      bottom: 0;
      right: 0;

      margin-bottom: 8px;
      margin-right: 8px;
    }

    #add-img {
      margin-top: 50px;
      margin-left: 250px;
    }

    a {
      text-decoration-line: none;
      text-decoration-style : none;
      color:white;
    }
  </style>

  <body>
    <div id="container">
      <div id="top-box">
        <div>
          {% if not user.is_authenticated %}
            <div style="display: flex; justify-content:right;">
              <div style="justify-content: right; text-align: right;">
                <a href="{% url 'account:signup' %}">회원가입</a><br>
                <a href="{% url 'account:login' %}">로그인</a>
              </div>
            </div>
          {% endif %}
          {% if user.is_authenticated %}
            <div style="display: flex; justify-content: right;">
              <a  href="{% url 'account:logout' %}">로그아웃</a>
            </div>
          {% endif %}
          <img id = "logo-img" src="{% static 'img/logo.png' %}" style = "width:100px;height:100px">

          
        </div>
        
        <!-- 검색어 기능이 있는 박스 -->
        <div id="search-box">
          <form method="GET" action="{% url 'template:search' %}">
            <input id="search" name="search" type="title" placeholder="템플릿을 검색하세요" />
          </form>
          
          <div id="img-box">
            <img
              id="search-img "
              src="{% static 'img/gg_search.png' %}"
              style="width: 35px; height: 35px"
            />
          </div>
        </div>

        <!-- 고침까지 -->
        <div id="btn-box">
          <button class="else-btn" onclick="location.href='/template/main/1/1'">학교</button>
          <button class="else-btn" onclick="location.href='/template/main/2/1'">동아리</button>
          <button class="else-btn" onclick="location.href='/template/main/3/1'">기본</button>
          <button class="else-btn" onclick="location.href='/template/main/4/1'">공유</button>
          <button class="else-btn" onclick="location.href='/contact/main/'">연락망</button>
        </div>
      </div>
      <!-- 여기안에 템플릿들 box,title생성 -->
      <div id="temp-contain">
        {% for temp in temps %}                
          <div class="smallContain" onclick="location.href='/template/mail/{{temp.id}}'">
            <div class="box">
              <h2>{{temp.title}}</h2>
              <a href="{% url 'template:updatePage' temp.id %}">
                <img
                  class="temp-edit-img"
                  src="{% static 'img/fePencil1.png' %}"
                  style="width:18px;height:18px"
                />
              </a>
            </div>
          </div>
        {% endfor %}
      </div>
      
    </div>
  </body>
</html>